os: Visual Studio 2015

environment:
  REDISRS_SERVER_TYPE: tcp
  RUST_BACKTRACE: 1
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  # N.B. redis-64 is a windows port of quite an old version of redis.
  # It has long been deprecated due to high-criticality defects.
  # Newer redis commands added to the crate are hidden behind features and will
  # not be tested here unless said features are explicitly enabled, but this
  # cannot happen until the method we use for running redis here changes.
  - cmd: nuget install redis-64 -excludeversion
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\redis-64\tools\

build: false

test_script:
  - cargo test --verbose --no-default-features --features tokio-comp %cargoflags%
